app = 'gefanimig-se'
primary_region = 'arn'

[build]

[env]
  NODE_ENV = 'production'

[metrics]
port = 9091
path = "/api/metrics"

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
  
  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'